prepend_path( "PATH",           pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","bin")   )
setenv( "LMOD_PNETCDF_BIN",     pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","bin")   )
setenv( "TACC_PNETCDF_BIN",     pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","lib")   )
setenv( "LMOD_PNETCDF_DIR",     "/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi"                     )
setenv( "LMOD_PNETCDF_INC",     pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","include")   )
setenv( "LMOD_PNETCDF_LIB",     pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","lib")   )
setenv( "TACC_PNETCDF_DIR",     "/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi"                     )
setenv( "TACC_PNETCDF_INC",     pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","include")   )
setenv( "TACC_PNETCDF_LIB",     pathJoin("/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/pnetcdf/installation-1.12.3-milan-gcc11-impi" )
