prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi","lib")   )
setenv( "LMOD_P4EST_DIR",     "/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi"                     )
setenv( "LMOD_P4EST_INC",     pathJoin("/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi","include")   )
setenv( "LMOD_P4EST_LIB",     pathJoin("/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi","lib")   )
setenv( "TACC_P4EST_DIR",     "/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi"                     )
setenv( "TACC_P4EST_INC",     pathJoin("/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi","include")   )
setenv( "TACC_P4EST_LIB",     pathJoin("/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi","lib")   )
prepend_path( "PKG_CONFIG_PATH", pathJoin( "/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi","lib/pkgconfig" ) )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/p4est/installation-2.8-milan-intel23-impi" )
