prepend_path(    "PATH",           pathJoin("/work/00434/eijkhout/trilinos/installation-13-4-1-milan-intel-impi","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/trilinos/installation-13-4-1-milan-intel-impi","lib64")   )
setenv( "LMOD_TRILINOS_DIR",     "/work/00434/eijkhout/trilinos/installation-13-4-1-milan-intel-impi"                     )
setenv( "LMOD_TRILINOS_INC",     pathJoin("/work/00434/eijkhout/trilinos/installation-13-4-1-milan-intel-impi","include")   )
setenv( "LMOD_TRILINOS_LIB",     pathJoin("/work/00434/eijkhout/trilinos/installation-13-4-1-milan-intel-impi","lib64")   )
setenv( "LMOD_TRILINOS_BIN",     pathJoin("/work/00434/eijkhout/trilinos/installation-13-4-1-milan-intel-impi","bin")   )
