prepend_path(    "PATH",           pathJoin("/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi","lib")   )
setenv( "LMOD_CXXOPTS_DIR",     "/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi"                     )
setenv( "LMOD_CXXOPTS_INC",     pathJoin("/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi","include")   )
setenv( "LMOD_CXXOPTS_LIB",     pathJoin("/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi","lib")   )
setenv( "LMOD_CXXOPTS_BIN",     pathJoin("/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi","bin")   )
prepend_path( "PKG_CONFIG_PATH", pathJoin( "/work/00434/eijkhout/cxxopts/installation-3.0.0-milan-oneapi","lib64/pkgconfig" ) )
