prepend_path(    "PATH",           pathJoin("/work/00434/eijkhout/warpx/installation-git-milan-gcc-impi","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/warpx/installation-git-milan-gcc-impi","lib")   )
setenv( "LMOD_WARPX_DIR",     "/work/00434/eijkhout/warpx/installation-git-milan-gcc-impi"                     )
setenv( "LMOD_WARPX_INC",     pathJoin("/work/00434/eijkhout/warpx/installation-git-milan-gcc-impi","include")   )
setenv( "LMOD_WARPX_LIB",     pathJoin("/work/00434/eijkhout/warpx/installation-git-milan-gcc-impi","lib")   )
setenv( "LMOD_WARPX_BIN",     pathJoin("/work/00434/eijkhout/warpx/installation-git-milan-gcc-impi","bin")   )
