prepend_path(    "PATH",           pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","lib")   )
setenv( "LMOD_GSL_DIR",     "/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc"                     )
setenv( "LMOD_GSL_INC",     pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","include")   )
setenv( "LMOD_GSL_LIB",     pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","lib")   )
setenv( "TACC_GSL_DIR",     "/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc"                     )
setenv( "TACC_GSL_INC",     pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","include")   )
setenv( "TACC_GSL_LIB",     pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","lib")   )
setenv( "LMOD_GSL_BIN",     pathJoin("/work/00434/eijkhout/gsl/installation-4.0.0-milan-gcc","bin")   )
