prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi","lib64")   )
setenv( "LMOD_TRILINOS_DIR",     "/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi"                     )
setenv( "LMOD_TRILINOS_INC",     pathJoin("/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi","include")   )
setenv( "LMOD_TRILINOS_LIB",     pathJoin("/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi","lib64")   )
setenv( "TACC_TRILINOS_DIR",     "/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi"                     )
setenv( "TACC_TRILINOS_INC",     pathJoin("/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi","include")   )
setenv( "TACC_TRILINOS_LIB",     pathJoin("/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi","lib64")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/trilinos/installation-13.4.1-milan-intel23-impi" )
