prepend_path( "PATH",           pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","bin")   )
setenv( "LMOD_PERIDIGM_BIN",     pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","bin")   )
setenv( "TACC_PERIDIGM_BIN",     pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","lib")   )
setenv( "LMOD_PERIDIGM_DIR",     "/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi"                     )
setenv( "LMOD_PERIDIGM_INC",     pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","include")   )
setenv( "LMOD_PERIDIGM_LIB",     pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","lib")   )
setenv( "TACC_PERIDIGM_DIR",     "/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi"                     )
setenv( "TACC_PERIDIGM_INC",     pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","include")   )
setenv( "TACC_PERIDIGM_LIB",     pathJoin("/work/00434/eijkhout/peridigm/installation-git-milan-intel-impi","lib")   )
