prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi","lib")   )
setenv( "LMOD_GKLIB_DIR",     "/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi"                     )
setenv( "LMOD_GKLIB_INC",     pathJoin("/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi","include")   )
setenv( "LMOD_GKLIB_LIB",     pathJoin("/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/gklib/installation-git-milan-intel23-impi" )
