prepend_path( "PATH",           pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","bin")   )
setenv( "LMOD_NETCDF_BIN",     pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","bin")   )
setenv( "TACC_NETCDF_BIN",     pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","lib")   )
setenv( "LMOD_NETCDF_DIR",     "/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi"                     )
setenv( "LMOD_NETCDF_INC",     pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","include")   )
setenv( "LMOD_NETCDF_LIB",     pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","lib")   )
setenv( "TACC_NETCDF_DIR",     "/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi"                     )
setenv( "TACC_NETCDF_INC",     pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","include")   )
setenv( "TACC_NETCDF_LIB",     pathJoin("/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/netcdf/installation-4.9.2-milan-intel23-impi" )
